### ISSUE TITLE
Possible incorrect information

### ISSUE THREAD

**Issue by erankova** [learn-co-curriculum/dsc-ml-interp-interpreting-whiteboxes#1]
## Link to Canvas

https://learning.flatironschool.com/courses/7217/pages/interpreting-white-boxes-building-a-decision-engine?module_item_id=644826

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ x] Other (explain below)

## Describe the Issue
"Both models had higher precision than recall, which suggests that the model may be slightly more sensitive than specific. In other words, we are more likely to see a false positive than a false negative." - this is either wrong or confusing because I think higher precision than recall means less false positives and more false negatives.
### Source

```
"Both models had higher precision than recall, which suggests that the model may be slightly more sensitive than specific. In other words, we are more likely to see a false positive than a false negative." 
```

### Concern

Potentially inaccurate information

## (Optional) Proposed Solution

Provide a deeper explanation or correct the error if it is an error

## What OS Are You Using?

- [x ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for flagging this, we'll take a look.

**Comment by danielburdeno** [comment]
language fixed/switch. Sensitivity is recall so false negatives more likely. Reworked how categorical features are handled using OHE, label encoding not appropriate for features.
